"""Photonics helper library — units, materials, fibers, pulses, FROG."""

from .base import (
    Wavelength,
    Frequency,
    AngularFrequency,
    Wavenumber,
    WavelengthArray,
    FrequencyArray,
    AngularFrequencyArray,
    WavenumberArray,
    Length,
    Time,
    Energy,
    Power,
    Area,
    Permittivity,
    Permiability,
    PI,
    C_MS,
    EPS_0,
    MU_0,
    H_PLANCK,
    HBAR,
)

from .materials import RefractiveIndex
from .fiber import Dispersion, PropagationConstant, ZDependentDispersion
from .pulse import (
    FROGTrace,
    generate_trace,
    retrieve,
    fidelity,
    Envelope,
    Wave,
    TemporalGrid,
)  # type: ignore
from .raman import (
    RamanSpec,
    RamanDatabase,
    RamanResponse,
    RamanFrequencyResponse,
    RamanPulseInteraction,
    PumpWavelengthExplorer,
    MaterialComparison,
    RAMAN_MATERIALS,
    COMMON_COMPARISONS,
    app,
)
from .phonon import PhononMode, PhononResponse, PHONON_MATERIALS
from .soliton import SolitonAnalyzer
from .gnlse import FiberProfile, GNLSESolver, SplitStepEngine, TaperedGNLSESolver
from .phase_matching import (
    DispersionModel,
    DispersionAdaptor,
    PropagationConstantAdaptor,
    ZDependentDispersionAdaptor,
    fwm_delta_beta_degenerate,
    fwm_delta_beta_general,
    fwm_efficiency,
    fwm_idler_frequency,
    scan_fwm_detuning,
    mi_gain_spectrum,
    mi_sideband_frequencies,
    mi_gain_spectrum_extended,
    dispersive_wave_roots,
    assess_simulation_readiness,
    compare_spectrum_to_phase_matching,
    PhaseMatchResult,
    DispersiveWaveResult,
    SimulationReadinessReport,
    ValidationReport,
    plot_fwm_efficiency,
    plot_mi_gain,
    plot_readiness_report,
    plot_spectrum_with_pm_overlay,
)

__all__ = [
    "Wavelength",
    "Frequency",
    "AngularFrequency",
    "Wavenumber",
    "WavelengthArray",
    "FrequencyArray",
    "AngularFrequencyArray",
    "WavenumberArray",
    "Length",
    "Time",
    "Energy",
    "Power",
    "Area",
    "Permittivity",
    "Permiability",
    "PI",
    "C_MS",
    "EPS_0",
    "MU_0",
    "H_PLANCK",
    "HBAR",
    "RefractiveIndex",
    "Dispersion",
    "PropagationConstant",
    "ZDependentDispersion",
    "FROGTrace",
    "generate_trace",
    "retrieve",
    "fidelity",
    "Envelope",
    "Wave",
    "TemporalGrid",
    "RamanSpec",
    "RamanDatabase",
    "RamanResponse",
    "RamanFrequencyResponse",
    "RamanPulseInteraction",
    "PumpWavelengthExplorer",
    "MaterialComparison",
    "RAMAN_MATERIALS",
    "COMMON_COMPARISONS",
    "app",
    "PhononMode",
    "PhononResponse",
    "PHONON_MATERIALS",
    "SolitonAnalyzer",
    "FiberProfile",
    "GNLSESolver",
    "SplitStepEngine",
    "TaperedGNLSESolver",
    "DispersionModel",
    "DispersionAdaptor",
    "PropagationConstantAdaptor",
    "ZDependentDispersionAdaptor",
    "fwm_delta_beta_degenerate",
    "fwm_delta_beta_general",
    "fwm_efficiency",
    "fwm_idler_frequency",
    "scan_fwm_detuning",
    "mi_gain_spectrum",
    "mi_sideband_frequencies",
    "mi_gain_spectrum_extended",
    "dispersive_wave_roots",
    "assess_simulation_readiness",
    "compare_spectrum_to_phase_matching",
    "PhaseMatchResult",
    "DispersiveWaveResult",
    "SimulationReadinessReport",
    "ValidationReport",
    "plot_fwm_efficiency",
    "plot_mi_gain",
    "plot_readiness_report",
    "plot_spectrum_with_pm_overlay",
]
