from __future__ import annotations
from typing import Literal, Self
from functools import cached_property
from numpy.typing import NDArray, ArrayLike

from pydantic.dataclasses import dataclass

PI: float
C_MS: float
EPS_0: float
MU_0: float
H_PLANCK: float
HBAR: float

@dataclass(config={"arbitrary_types_allowed": True})
class Wavelength:
    value: float
    unit: Literal["nm", "um", "m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_m(self) -> float: ...
    @cached_property
    def as_um(self) -> float: ...
    @cached_property
    def as_nm(self) -> float: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_energy(self) -> Energy: ...
    def to_wn(self) -> Wavenumber: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Frequency:
    value: float
    unit: Literal["THz", "GHz", "MHz", "Hz"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_Hz(self) -> float: ...
    @cached_property
    def as_THz(self) -> float: ...
    @cached_property
    def as_GHz(self) -> float: ...
    @cached_property
    def as_MHz(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_wn(self) -> Wavenumber: ...
    def to_time(self) -> Time: ...
    def to_energy(self) -> Energy: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class AngularFrequency:
    value: float
    unit: Literal["rad/s", "rad/ps"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_rad_s(self) -> float: ...
    @cached_property
    def as_rad_ps(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_freq(self) -> Frequency: ...
    def to_wn(self) -> Wavenumber: ...
    def to_time(self) -> Time: ...
    def to_energy(self) -> Energy: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Wavenumber:
    value: float
    unit: Literal["1/cm", "1/m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_1_m(self) -> float: ...
    @cached_property
    def as_1_cm(self) -> float: ...
    @cached_property
    def as_angular(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_energy(self) -> Energy: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Length:
    value: float
    unit: Literal["km", "m", "cm", "mm", "um", "nm", "pm"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_km(self) -> float: ...
    @cached_property
    def as_m(self) -> float: ...
    @cached_property
    def as_cm(self) -> float: ...
    @cached_property
    def as_mm(self) -> float: ...
    @cached_property
    def as_um(self) -> float: ...
    @cached_property
    def as_nm(self) -> float: ...
    @cached_property
    def as_pm(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    @classmethod
    def from_wl(cls, wl: Wavelength) -> Self: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Time:
    value: float
    unit: Literal["s", "ms", "us", "ns", "ps", "fs", "as"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_s(self) -> float: ...
    @cached_property
    def as_ms(self) -> float: ...
    @cached_property
    def as_us(self) -> float: ...
    @cached_property
    def as_ns(self) -> float: ...
    @cached_property
    def as_ps(self) -> float: ...
    @cached_property
    def as_fs(self) -> float: ...
    @cached_property
    def as_as(self) -> float: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...
    @classmethod
    def from_freq(cls, freq: Frequency) -> Self: ...
    @classmethod
    def from_omega(cls, omega: AngularFrequency) -> Self: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Energy:
    value: float
    unit: Literal["J", "mJ", "uJ", "nJ", "pJ", "eV", "meV"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_J(self) -> float: ...
    @cached_property
    def as_mJ(self) -> float: ...
    @cached_property
    def as_uJ(self) -> float: ...
    @cached_property
    def as_nJ(self) -> float: ...
    @cached_property
    def as_pJ(self) -> float: ...
    @cached_property
    def as_eV(self) -> float: ...
    @cached_property
    def as_meV(self) -> float: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_wl(self) -> Wavelength: ...
    def to_wn(self) -> Wavenumber: ...
    @classmethod
    def from_freq(cls, freq: Frequency) -> Self: ...
    @classmethod
    def from_omega(cls, omega: AngularFrequency) -> Self: ...
    @classmethod
    def from_wl(cls, wl: Wavelength) -> Self: ...
    @classmethod
    def from_wn(cls, wn: Wavenumber) -> Self: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Power:
    value: float
    unit: Literal["kW", "W", "mW", "uW", "nW"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_kW(self) -> float: ...
    @cached_property
    def as_W(self) -> float: ...
    @cached_property
    def as_mW(self) -> float: ...
    @cached_property
    def as_uW(self) -> float: ...
    @cached_property
    def as_nW(self) -> float: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Area:
    value: float
    unit: Literal["m^2", "cm^2", "mm^2", "um^2", "nm^2"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @cached_property
    def as_m2(self) -> float: ...
    @cached_property
    def as_cm2(self) -> float: ...
    @cached_property
    def as_mm2(self) -> float: ...
    @cached_property
    def as_um2(self) -> float: ...
    @cached_property
    def as_nm2(self) -> float: ...
    @classmethod
    def from_meep(cls, value: float, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> float: ...

@dataclass(config={"arbitrary_types_allowed": True})
class WavelengthArray:
    value: ArrayLike
    unit: Literal["nm", "um", "m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_m(self) -> NDArray: ...
    @cached_property
    def as_um(self) -> NDArray: ...
    @cached_property
    def as_nm(self) -> NDArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...
    @classmethod
    def from_meep(cls, value: float | NDArray, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class FrequencyArray:
    value: ArrayLike
    unit: Literal["THz", "GHz", "MHz", "Hz"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_Hz(self) -> NDArray: ...
    @cached_property
    def as_THz(self) -> NDArray: ...
    @cached_property
    def as_GHz(self) -> NDArray: ...
    @cached_property
    def as_MHz(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...
    @classmethod
    def from_meep(cls, value: float | NDArray, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class AngularFrequencyArray:
    value: ArrayLike
    unit: Literal["rad/s", "rad/ps"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_rad_s(self) -> NDArray: ...
    @cached_property
    def as_rad_ps(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...
    @classmethod
    def from_meep(cls, value: float | NDArray, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class WavenumberArray:
    value: ArrayLike
    unit: Literal["1/cm", "1/m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_1_m(self) -> NDArray: ...
    @cached_property
    def as_1_cm(self) -> NDArray: ...
    @cached_property
    def as_angular(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...
    @classmethod
    def from_meep(cls, value: float | NDArray, base_length: Wavelength | None = None) -> Self: ...
    @cached_property
    def as_meep(self) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Permittivity(float):
    value: float
    def __post_init__(self) -> None: ...
    @classmethod
    def from_relative(cls, relative_value: float) -> Permittivity: ...
    def __repr__(self) -> str: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Permiability(float):
    value: float
    def __post_init__(self) -> None: ...
    @classmethod
    def from_relative(cls, relative_value: float) -> Permiability: ...
    def __repr__(self) -> str: ...
