from __future__ import annotations
from typing import Literal, Self
from functools import cached_property
from numpy.typing import NDArray, ArrayLike

import numpy as np
from pydantic.dataclasses import dataclass

PI: float
C_MS: float
EPS_0: float
MU_0: float

@dataclass(config={"arbitrary_types_allowed": True})
class Wavelength:
    value: float
    unit: Literal["nm", "um", "m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_m(self) -> float: ...
    @cached_property
    def as_um(self) -> float: ...
    @cached_property
    def as_nm(self) -> float: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_wn(self) -> Wavenumber: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Frequency:
    value: float
    unit: Literal["THz", "GHz", "MHz", "Hz"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_Hz(self) -> float: ...
    @cached_property
    def as_THz(self) -> float: ...
    @cached_property
    def as_GHz(self) -> float: ...
    @cached_property
    def as_MHz(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_omega(self) -> AngularFrequency: ...
    def to_wn(self) -> Wavenumber: ...

@dataclass(config={"arbitrary_types_allowed": True})
class AngularFrequency:
    value: float
    unit: Literal["rad/s", "rad/ps"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_rad_s(self) -> float: ...
    @cached_property
    def as_rad_ps(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_freq(self) -> Frequency: ...
    def to_wn(self) -> Wavenumber: ...

@dataclass(config={"arbitrary_types_allowed": True})
class Wavenumber:
    value: float
    unit: Literal["1/cm", "1/m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_1_m(self) -> float: ...
    @cached_property
    def as_1_cm(self) -> float: ...
    @cached_property
    def as_angular(self) -> float: ...
    def to_wl(self) -> Wavelength: ...
    def to_freq(self) -> Frequency: ...
    def to_omega(self) -> AngularFrequency: ...

@dataclass(config={"arbitrary_types_allowed": True})
class WavelengthArray:
    value: ArrayLike
    unit: Literal["nm", "um", "m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_m(self) -> NDArray: ...
    @cached_property
    def as_um(self) -> NDArray: ...
    @cached_property
    def as_nm(self) -> NDArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class FrequencyArray:
    value: ArrayLike
    unit: Literal["THz", "GHz", "MHz", "Hz"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_Hz(self) -> NDArray: ...
    @cached_property
    def as_THz(self) -> NDArray: ...
    @cached_property
    def as_GHz(self) -> NDArray: ...
    @cached_property
    def as_MHz(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class AngularFrequencyArray:
    value: ArrayLike
    unit: Literal["rad/s", "rad/ps"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_rad_s(self) -> NDArray: ...
    @cached_property
    def as_rad_ps(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_wn(self) -> WavenumberArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...

@dataclass(config={"arbitrary_types_allowed": True})
class WavenumberArray:
    value: ArrayLike
    unit: Literal["1/cm", "1/m"]
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @cached_property
    def as_1_m(self) -> NDArray: ...
    @cached_property
    def as_1_cm(self) -> NDArray: ...
    @cached_property
    def as_angular(self) -> NDArray: ...
    def to_wl(self) -> WavelengthArray: ...
    def to_freq(self) -> FrequencyArray: ...
    def to_omega(self) -> AngularFrequencyArray: ...
    def to_equally_spaced(self, points: int = 51) -> NDArray: ...
