from __future__ import annotations

from typing import Literal

from numpy.typing import NDArray

from photonics_helper.base import Wavelength, WavelengthArray
from photonics_helper.materials import RefractiveIndex

class Material:
    name: str
    refractive_index: RefractiveIndex

    def n_func(self, wavelength: float) -> float: ...
    def k_func(self, wavelength: float) -> float: ...

class Block:
    length: float
    material: Material
    colour: str | None
    _position: tuple[float, float] | None

    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def position(self) -> tuple[float, float] | None: ...
    @position.setter
    def position(self, value: tuple[float, float]) -> None: ...
    @position.deleter
    def position(self) -> None: ...

class Pattren:
    style: str
    mapping: dict[str, Block]
    central_wavelength: Wavelength | None
    _length: float
    _out: list[Block]

    def __post_init__(self) -> None: ...
    @property
    def out(self) -> list[Block]: ...
    @out.deleter
    def out(self) -> None: ...
    @property
    def length(self) -> float: ...
    def make_pattren(self) -> None: ...
    def add_block(self, block: Block, mapping: str, index: int) -> None: ...
    def remove_block(self, index: int) -> None: ...
    def get_index(self, wl_micron: float) -> tuple[list[float], list[float]]: ...
    def _get_lengths(self) -> list[float]: ...
    def _get_positions(self) -> list[tuple[float, float] | None]: ...
    def _get_colours(self) -> list[str | None]: ...
    def _get_names(self, type: int = ...) -> list[str]: ...
    def plot_index(self, wl: Wavelength | None = ...) -> None: ...
    def plot_2d(self, height: float = ..., overlay_index: bool = ...) -> None: ...

class TMM:
    pattern: Pattren
    angle_of_incidence: float
    polarisation: Literal["TE", "TM"]

    def _characteristic_matrix(
        self, letter_asigned: str, wavelength: Wavelength
    ) -> NDArray: ...
    def transfer_matrix(self, wavelength: Wavelength) -> NDArray: ...
    def spectrum(self, wavelengths: WavelengthArray) -> tuple[NDArray, NDArray]: ...
    def _admittance(self, n: complex, angle: float) -> complex: ...
    def _reflection_coefficient(self, wavelength: Wavelength) -> complex: ...
    def field_profile(self, wavelength: Wavelength) -> NDArray: ...

def plot_index(pattren: Pattren, wl: Wavelength) -> None: ...
def plot_2d(
    pattren: Pattren, height: float = ..., overlay_index: bool = ...
) -> None: ...
