"""Reference Raman material tables (hardcoded fallback data)."""

from __future__ import annotations

RAMAN_MATERIALS: dict[str, dict] = {
    "Silica": {
        "name": "Silica",
        "crystal": "Amorphous SiO2",
        "bandgap_eV": 9.0,
        "n2": 3.2e-20,
        "raman_shift_cm": 440,
        "raman_linewidth_cm": 45,
        "fR": 0.18,
        "gain_coeff": 1.0e-13,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Agrawal, Nonlinear Fiber Optics, 5th ed.",
    },
    "CdS": {
        "name": "CdS",
        "crystal": "Wurtzite",
        "bandgap_eV": 2.42,
        "n2": 1.5e-18,
        "raman_shift_cm": 305,
        "raman_linewidth_cm": 12,
        "fR": 0.35,
        "gain_coeff": None,
        "lo_phonon_cm": 302,
        "to_phonon_cm": 293,
        "references": "Pankove, Optical Processes in Semiconductors",
    },
    "GaAs": {
        "name": "GaAs",
        "crystal": "Zincblende",
        "bandgap_eV": 1.42,
        "n2": 2.5e-18,
        "raman_shift_cm": 292,
        "raman_linewidth_cm": 5,
        "fR": 0.07,
        "gain_coeff": None,
        "lo_phonon_cm": 292,
        "to_phonon_cm": 268,
        "references": "Adachi, Optical Properties of Crystalline and Amorphous Semiconductors",
    },
    "Diamond": {
        "name": "Diamond",
        "crystal": "Diamond cubic",
        "bandgap_eV": 5.5,
        "n2": 1.1e-19,
        "raman_shift_cm": 1332,
        "raman_linewidth_cm": 4,
        "fR": 0.0,
        "gain_coeff": 0.11,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Ferrari, Raman spectroscopy of graphene and graphite",
    },
    "LiNbO3": {
        "name": "LiNbO3",
        "crystal": "Rhombohedral",
        "bandgap_eV": 3.7,
        "n2": 3.0e-20,
        "raman_shift_cm": 254,
        "raman_linewidth_cm": 14,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Fejer, Quasi-phase-matched nonlinear optics",
    },
    "As2Se3": {
        "name": "As2Se3",
        "crystal": "Amorphous",
        "bandgap_eV": 1.8,
        "n2": 3.5e-18,
        "raman_shift_cm": 310,
        "raman_linewidth_cm": 60,
        "fR": 0.55,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Richardson, Chalcogenide glass fibers for nonlinear optics",
    },
    "Si": {
        "name": "Si",
        "crystal": "Diamond cubic",
        "bandgap_eV": 1.12,
        "n2": 6.0e-19,
        "raman_shift_cm": 520,
        "raman_linewidth_cm": 4,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Burstein, Infrared and Raman studies of silicon",
    },
    "Ge": {
        "name": "Ge",
        "crystal": "Diamond cubic",
        "bandgap_eV": 0.67,
        "n2": 1.2e-18,
        "raman_shift_cm": 300,
        "raman_linewidth_cm": 8,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Nakamura, Raman scattering in germanium",
    },
    "As2S3": {
        "name": "As2S3",
        "crystal": "Amorphous",
        "bandgap_eV": 2.0,
        "n2": 4.0e-18,
        "raman_shift_cm": 345,
        "raman_linewidth_cm": 56,
        "fR": 0.15,
        "gain_coeff": 4.3e-12,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Xiong et al., Appl. Opt. 48, 5467 (2009); Slusher et al., JOSA B 21, 1146 (2004)",
    },
    "Si3N4": {
        "name": "Si3N4",
        "crystal": "Amorphous/hexagonal",
        "bandgap_eV": 4.9,
        "n2": 2.4e-19,
        "raman_shift_cm": 206,
        "raman_linewidth_cm": 50,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Zymla et al., J. Raman Spectrosc. (2025); Lacava et al., Sci. Rep. 7, 41598 (2017)",
    },
    "Si3N4-Ligentec": {
        "name": "Si3N4-Ligentec",
        "crystal": "Amorphous (LPCVD stoichiometric, Ligentec platform)",
        "bandgap_eV": 4.9,
        "n2": 2.4e-19,
        "raman_shift_cm": 206,
        "raman_linewidth_cm": 50,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Rehan et al., ACS Photonics (2025), arXiv:2501.10575 (n≈2.0 @1550nm); base Sellmeier fit Luke et al., Opt. Express 23, 22808 (2015)",
    },
    "SiC_4H": {
        "name": "SiC_4H",
        "crystal": "Hexagonal (4H)",
        "bandgap_eV": 3.23,
        "n2": 8.0e-19,
        "raman_shift_cm": 777,
        "raman_linewidth_cm": 5,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": 983,
        "to_phonon_cm": 777,
        "references": "Feldman et al., Phys. Rev. 173, 787 (1968); Li et al., Phys. Rev. Appl. 19, 034083 (2023)",
    },
    "YAG": {
        "name": "YAG",
        "crystal": "Cubic garnet",
        "bandgap_eV": 6.5,
        "n2": 7.0e-20,
        "raman_shift_cm": 784,
        "raman_linewidth_cm": 8,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Hurrell et al., Phys. Rev. 173, 851 (1968); Lamaignere et al., Opt. Mater. X 8, 100068 (2020)",
    },
    "BaTiO3": {
        "name": "BaTiO3",
        "crystal": "Tetragonal perovskite",
        "bandgap_eV": 3.2,
        "n2": 1.8e-18,
        "raman_shift_cm": 520,
        "raman_linewidth_cm": 45,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Scalabrin et al., Phys. Status Solidi B 79, 731 (1977); Chaves et al., Phys. Rev. B 10, 3522 (1974)",
    },
    "ZBLAN": {
        "name": "ZBLAN",
        "crystal": "Amorphous fluoride",
        "bandgap_eV": 4.5,
        "n2": 1.5e-20,
        "raman_shift_cm": 580,
        "raman_linewidth_cm": 23,
        "fR": 0.06,
        "gain_coeff": 4.0e-14,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Petersen et al., JOSA B 28, 2310 (2011); Yan et al., JOSA B 29, 238 (2012)",
    },
    "GaN": {
        "name": "GaN",
        "crystal": "Wurtzite",
        "bandgap_eV": 3.4,
        "n2": 9.0e-19,
        "raman_shift_cm": 568,
        "raman_linewidth_cm": 4,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": 736,
        "to_phonon_cm": 532,
        "references": "Zeng et al., Appl. Sci. 10, 8814 (2020); Almeida et al., Photonics 6, 69 (2019)",
    },
    "AlN": {
        "name": "AlN",
        "crystal": "Wurtzite",
        "bandgap_eV": 6.2,
        "n2": 2.3e-19,
        "raman_shift_cm": 658,
        "raman_linewidth_cm": 1,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": 895,
        "to_phonon_cm": 615,
        "references": "Pandit et al., J. Appl. Phys. 102, 113508 (2007); Jung, Tang, Nanophotonics 5, 264 (2016)",
    },
    "InP": {
        "name": "InP",
        "crystal": "Zincblende",
        "bandgap_eV": 1.34,
        "n2": 2.0e-17,
        "raman_shift_cm": 345,
        "raman_linewidth_cm": 3,
        "fR": 0.05,
        "gain_coeff": None,
        "lo_phonon_cm": 345,
        "to_phonon_cm": 307,
        "references": "Artus et al., Phys. Rev. B 50, 11552 (1994); Mobini et al., J. Phys. Photonics (2026)",
    },
    "LiTaO3": {
        "name": "LiTaO3",
        "crystal": "Rhombohedral",
        "bandgap_eV": 4.0,
        "n2": 3.0e-20,
        "raman_shift_cm": 255,
        "raman_linewidth_cm": 12,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Raptis, Phys. Rev. B 38, 10007 (1988); Margueron et al., J. Appl. Phys. 111, 104105 (2012)",
    },
    "KTP": {
        "name": "KTP",
        "crystal": "Orthorhombic (Pna2_1)",
        "bandgap_eV": 3.5,
        "n2": 5.0e-20,
        "raman_shift_cm": 270,
        "raman_linewidth_cm": 20,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Neufeld et al., Crystals 13, 1423 (2023)",
    },
    "AlGaAs": {
        "name": "AlGaAs",
        "crystal": "Zincblende",
        "bandgap_eV": 1.65,
        "n2": 2.0e-17,
        "raman_shift_cm": 284,
        "raman_linewidth_cm": 5,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": 284,
        "to_phonon_cm": 262,
        "references": "Feng et al., Phys. Rev. B 47, 13466 (1993); Villeneuve et al., Appl. Phys. Lett. 62, 2465 (1993)",
    },
    "Al2O3": {
        "name": "Al2O3",
        "crystal": "Corundum",
        "bandgap_eV": 8.8,
        "n2": 3.1e-20,
        "raman_shift_cm": 418,
        "raman_linewidth_cm": 5,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Watson et al., J. Chem. Phys. 74, 2023 (1981); Major et al., Opt. Lett. 29, 602 (2004)",
    },
    "YLF": {
        "name": "YLF",
        "crystal": "Scheelite (tetragonal)",
        "bandgap_eV": 10.0,
        "n2": 1.7e-20,
        "raman_shift_cm": 262,
        "raman_linewidth_cm": 5,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Miller et al., J. Chem. Phys. 52, 4172 (1970); Salaun et al., J. Phys. Condens. Matter 9, 6941 (1997)",
    },
    "ZnO": {
        "name": "ZnO",
        "crystal": "Wurtzite",
        "bandgap_eV": 3.37,
        "n2": -9.0e-19,
        "raman_shift_cm": 439,
        "raman_linewidth_cm": 7,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": 574,
        "to_phonon_cm": 380,
        "references": "Cusco et al., Phys. Rev. B 75, 165202 (2007); Zhang et al., JOSA B 14, 1951 (1997)",
    },
    "CdTe": {
        "name": "CdTe",
        "crystal": "Zincblende",
        "bandgap_eV": 1.44,
        "n2": -3.0e-17,
        "raman_shift_cm": 166,
        "raman_linewidth_cm": 15,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": 166,
        "to_phonon_cm": 141,
        "references": "Tivanov et al., J. Mater. Sci. (2025); Sayadov et al., JOSA B 9, 405 (1992)",
    },
    "Ga2O3": {
        "name": "Ga2O3",
        "crystal": "Monoclinic (beta)",
        "bandgap_eV": 4.85,
        "n2": 4.0e-19,
        "raman_shift_cm": 767,
        "raman_linewidth_cm": 5,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Kranert et al., Sci. Rep. 6, 35964 (2016); Sun et al., Appl. Phys. Lett. (2022)",
    },
    "LBO": {
        "name": "LBO",
        "crystal": "Orthorhombic",
        "bandgap_eV": 7.8,
        "n2": 1.0e-20,
        "raman_shift_cm": 938,
        "raman_linewidth_cm": 15,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Chen et al., JOSA B 6, 616 (1989)",
    },
    "AgGaS2": {
        "name": "AgGaS2",
        "crystal": "Chalcopyrite (tetragonal)",
        "bandgap_eV": 2.73,
        "n2": 3.0e-18,
        "raman_shift_cm": 295,
        "raman_linewidth_cm": 5,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Lockwood, Montgomery, J. Phys. C 8 (1975); Qiao et al., Opt. Mater. 119, 111300 (2021)",
    },
    "AgGaSe2": {
        "name": "AgGaSe2",
        "crystal": "Chalcopyrite (tetragonal)",
        "bandgap_eV": 1.82,
        "n2": 5.0e-18,
        "raman_shift_cm": 180,
        "raman_linewidth_cm": 5,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Miller et al., Phys. Status Solidi B 78, 569 (1976)",
    },
    "InGaAs": {
        "name": "InGaAs",
        "crystal": "Zincblende",
        "bandgap_eV": 0.75,
        "n2": 5.0e-17,
        "raman_shift_cm": 269,
        "raman_linewidth_cm": 5,
        "fR": None,
        "gain_coeff": None,
        "lo_phonon_cm": 269,
        "to_phonon_cm": 255,
        "references": "Estrera et al., J. Appl. Phys. 72, 3692 (1992); Zhang et al., Appl. Phys. Lett. 123, 011103 (2023)",
    },
    "GeO2": {
        "name": "GeO2",
        "crystal": "Amorphous",
        "bandgap_eV": 5.5,
        "n2": 6.0e-20,
        "raman_shift_cm": 420,
        "raman_linewidth_cm": 135,
        "fR": 0.20,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Davey et al., IEE Proc. J 136, 301 (1989); Bromage et al., IEEE Photon. Technol. Lett. 14, 24 (2002)",
    },
    "GeAsSe": {
        "name": "GeAsSe",
        "crystal": "Amorphous",
        "bandgap_eV": 1.6,
        "n2": 6.0e-18,
        "raman_shift_cm": 250,
        "raman_linewidth_cm": 50,
        "fR": 0.50,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Richardson, Chalcogenide glass fibers for nonlinear optics; ~2× As2Se3 (Slusher et al., JOSA B 21, 1146)",
    },
}

# Thorlabs optical substrates (refractive index / Sellmeier; no Raman response)
# https://www.thorlabs.com/optical-substrates
THORLABS_SUBSTRATE_MATERIALS: dict[str, dict] = {
    "N-BK7": {
        "name": "N-BK7",
        "crystal": "Borosilicate crown glass",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; SCHOTT N-BK7 (refractiveindex.info)",
    },
    "N-SF11": {
        "name": "N-SF11",
        "crystal": "Dense flint glass",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; SCHOTT N-SF11 (refractiveindex.info)",
    },
    "N-F2": {
        "name": "N-F2",
        "crystal": "Flint glass",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; SCHOTT N-F2 (refractiveindex.info)",
    },
    "F2": {
        "name": "F2",
        "crystal": "Flint glass",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; SCHOTT F2 (refractiveindex.info)",
    },
    "CaF2": {
        "name": "CaF2",
        "crystal": "Cubic (fluorite)",
        "bandgap_eV": 12.1,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Daimon & Masumura, Appl. Opt. 41, 5275 (2002)",
    },
    "BaF2": {
        "name": "BaF2",
        "crystal": "Cubic",
        "bandgap_eV": 10.2,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Malitson, JOSA 54, 628 (1964)",
    },
    "MgF2": {
        "name": "MgF2",
        "crystal": "Tetragonal (o-ray, c-axis oriented)",
        "bandgap_eV": 12.0,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Dodge, Appl. Opt. 23, 1980 (1984)",
    },
    "ZnSe": {
        "name": "ZnSe",
        "crystal": "Zincblende",
        "bandgap_eV": 2.70,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Marple, J. Appl. Phys. 35, 539 (1964)",
    },
    "YVO4": {
        "name": "YVO4",
        "crystal": "Tetragonal (o-ray)",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Birnbaum & DeShazer, NASA CR (1976)",
    },
    "KBr": {
        "name": "KBr",
        "crystal": "Cubic",
        "bandgap_eV": 7.5,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Li, J. Phys. Chem. Ref. Data 5, 329 (1976)",
    },
    "Zerodur": {
        "name": "Zerodur",
        "crystal": "Glass ceramic",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; SCHOTT ZERODUR (refractiveindex.info)",
    },
    "PMMA": {
        "name": "PMMA",
        "crystal": "Amorphous (acrylic)",
        "bandgap_eV": None,
        "n2": None,
        "raman_shift_cm": None,
        "raman_linewidth_cm": None,
        "fR": 0.0,
        "gain_coeff": None,
        "lo_phonon_cm": None,
        "to_phonon_cm": None,
        "references": "Thorlabs Optical Substrates; Szczurowski (refractiveindex.info)",
    },
}
