"""Reproduction: spatiotemporal modulation instability (STMI) sidebands in a
GRIN multimode fibre (Wright et al. 2015).

Reference
---------
L. G. Wright, Z. Liu, D. A. Nolan, M.-J. Li, D. N. Christodoulides &
F. W. Wise, "Self-organized instability in graded-index multimode fibres",
Nat. Photonics 10, 471-476 (2016), doi:10.1038/nphoton.2015.60
(arXiv:1603.07414).

What is reproduced
------------------
The paper's central nonlinear effect after beam-cleanup is spatiotemporal
modulation instability (STMI): once the field has self-organized to the
attractor (fundamental mode of the 13-um GRIN fibre, ~1.5 uJ / ~1 ns pulses
at 532 nm), cascades of FWM sidebands appear whose frequencies are fixed by
GRIN-modulated phase matching (paper Figs. 1, 3).  Fig. 3d shows the averaged
sideband shifts vs "MI order"; the theory family there is the modal-ladder
spatiotemporal phase matching of the GRIN fibre.

Checks
------
1. ANALYTIC (paper Fig. 3d): with the paraxial GRIN ladder
   beta_N(w) ~ beta0(w) - N*kappa (kappa = sqrt(2*Delta)/a), the
   signal/idler pair of ladder order N at +-Omega phase-matches through the
   symmetric material-dispersion sum

       Delta(Omega) = beta0(w0+O) + beta0(w0-O) - 2 beta0(w0)
                      - 2 N kappa + 2 gamma_f P0 = 0,

   evaluated with real fused-silica Sellmeier dispersion.  The roots track
   the digitized Fig. 3d circles to <=~11 % for orders N = 2..5 (the paper's
   hyperbolic |Omega| ~ sqrt(N) branch).
2. ENGINE: a 3-channel multimode run — CW pump in the fundamental + a
   white-noise-seeded degenerate sideband pair carrying the GRIN modal phase
   through ``phase_offsets`` = -N*kappa (the same mechanism validated by the
   Krupa GPI reproduction) — develops stable spectral peaks at the analytic
   Omega_N to within 3 % (grid resolution 0.05 THz).
3. ENERGY: total photon bookkeeping conserved over the FWM runs to < 2 %.

Model caveats (documented, not hidden)
--------------------------------------
- The engine's retarded-frame Taylor starts at beta2; the ladder phase is
  injected via ``phase_offsets`` (the discrete-modal-grating mechanism).
- Only symmetric (signal+idler) observables are asserted, so the open
  ISSUES.md #0 dispersion time-direction convention (odd-order terms) is not
  exercised by these checks.
- The order-(-1) circle of Fig. 3d (+2 THz) is generated by the Stokes
  sidebands acting as pumps (theory family Stokes-1/2 in the same panel); it
  is NOT on the chromatic ladder and is recorded, not asserted.
- The full self-organized instability cascade (55 modes, disorder/Raman
  mode-coupling network, Fig. 4 attractor-gain comparison across 11 spatial
  seeds) is out of scope: this reproduction validates the STMI phase-matching
  backbone on the experiment's own fibre parameters.

Usage
-----
    python reproductions/planned/wright_2015_self_organized_instability/reproduce.py
"""

from __future__ import annotations

import json
from math import factorial
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from numpy.typing import NDArray
from scipy.optimize import brentq

from photonics_helper.base import Area, Length, Time, Wavelength
from photonics_helper.gnlse import FiberProfile
from photonics_helper.multimode_gnlse import MultimodeSplitStepEngine
from photonics_helper.pulse import Envelope, TemporalGrid, Wave

HERE = Path(__file__).resolve().parent
PARAMETERS = HERE / "parameters.json"

C_MS = 299792458.0
C_THZ = 299.792458  # THz * um

# --- fibre (Methods, PDF p-11; caption Delta) -------------------------------
LAMBDA0_NM = 532.0
LAMBDA0 = LAMBDA0_NM * 1e-9
R_CORE = 13.0e-6  # m
DELTA = 0.0064
N2 = 3.0e-20  # m^2/W
KAPPA = float(np.sqrt(2.0 * DELTA) / R_CORE)  # rad/m, paraxial ladder slope
MFD0 = 12.0e-6  # attractor mode-field diameter (paper Fig. 1b)
A_EFF = float(np.pi * (MFD0 / 2.0) ** 2)
P0_W = 1500.0  # 1.5 uJ / 1 ns
N_MODES = 3  # pump + degenerate sideband pair
# The gain bandwidth of the ladder resonance is narrow (|delta_kappa| <
# 2*gamma_eff*P0 ~ 6.3 rad/m -> +-0.021 THz of half-width at +-82 THz), so
# the spectral grid must resolve it: window 50 ps -> df = 0.02 THz.
WINDOW_PS = 50.0
N_GRID = 65536
NOISE_SEED = 20160471

# engine steps: the ladder phase rotates at N*kappa rad/m, so the FWM runs
# need dz small enough that Delta*beta0*dz ~< 0.4 rad/step for RK4 accuracy.
STEP_M_LADDER = 4.0e-5
NUM_STEPS_LADDER = 25000  # 1.0 m (length/step drives the loop count)
STEP_M_BASE = 1.0e-3
NUM_STEPS_BASE = 1000  # 1 m, offsets zero -> cheap

# --- paper Fig. 3d circles, digitized (abs shift in THz vs |MI order|) -----
PAPER_CIRCLES = {5: 188.0, 4: 165.0, 2: 110.0, 1: 65.0}
# order -1 circle (Stokes-pump branch, not on the chromatic ladder):
PAPER_STOKES_ORDER1_THZ = 2.0

# --- Sellmeier, fused silica (Malitson) ------------------------------------
SL_B = (0.6961663, 0.4079426, 0.8974794)
SL_C = (0.0684043**2, 0.1162414**2, 9.896161**2)

PUMP_THZ = C_THZ / 0.532


# ---------------------------------------------------------------------------
# material dispersion (real Sellmeier)
# ---------------------------------------------------------------------------


def n_silica(f_thz: float) -> float:
    """Fused-silica refractive index at frequency f (THz)."""
    wl_um = C_THZ / f_thz
    l2 = wl_um**2
    return float(
        np.sqrt(1.0 + sum(b * l2 / (l2 - c) for b, c in zip(SL_B, SL_C)))
    )


def beta0(f_thz: float) -> float:
    """Material propagation constant beta0(omega) in rad/m at f (THz)."""
    wl_um = C_THZ / f_thz
    return float(2.0 * np.pi * n_silica(f_thz) / (wl_um * 1e-6))


def beta1_silica(lambda_um: float) -> float:
    """beta1(omega) = d beta0/d omega (s/m), central differences in lambda."""
    h = 1e-4  # um
    om_hi = 2.0 * np.pi * C_MS / ((lambda_um - h) * 1e-6)
    om_lo = 2.0 * np.pi * C_MS / ((lambda_um + h) * 1e-6)
    b_hi = beta0(C_THZ / (lambda_um - h))
    b_lo = beta0(C_THZ / (lambda_um + h))
    return float((b_hi - b_lo) / (om_hi - om_lo))


def beta2_silica(lambda_nm: float) -> float:
    """beta2 (s^2/m) numerically from Sellmeier at lambda (nm)."""
    lam_um = lambda_nm / 1000.0
    h = 2e-3  # um
    dom = 2.0 * np.pi * C_MS * (
        1.0 / ((lam_um - h) * 1e-6) - 1.0 / ((lam_um + h) * 1e-6)
    )  # rad/s, NEGATIVE for lambda increasing (red)
    db1_dlam = (
        beta1_silica(lam_um + h) - beta1_silica(lam_um - h)
    ) / (2.0 * h)  # s/m per um (beta1 decreases toward blue)
    # dom = omega(lam-h) - omega(lam+h) over 2h  ->  d omega/d lambda = -dom/(2h)
    return float(-(2.0 * h) * db1_dlam / dom)  # d beta1 / d omega


# ---------------------------------------------------------------------------
# analytic STMI phase matching (the backbone of paper Fig. 3d)
# ---------------------------------------------------------------------------


def gamma_eff() -> float:
    """(2/3) gamma — lp_degenerate XPM/FWM weight of the degenerate pair."""
    return (2.0 / 3.0) * 2.0 * np.pi * N2 / LAMBDA0 / A_EFF


def delta_kappa(om_thz: float, n_ord: int) -> float:
    """Total pair mismatch per channel at detuning Omega (THz), rad/m.

    Delta = 0.5*(symmetric material sum) - N kappa + gamma_f P0
    (the phase-matching condition is the pairwise sum + 2 gamma_f P0).
    """
    sym = (
        beta0(PUMP_THZ + om_thz) + beta0(PUMP_THZ - om_thz)
        - 2.0 * beta0(PUMP_THZ)
    )
    return 0.5 * sym - n_ord * KAPPA + gamma_eff() * P0_W


def stmi_shift_thz_corrected(n_ord: int, om_lo=0.5, om_hi=270.0) -> float:
    """Corrected-machine analytic root (ISSUES.md #10 resolution).

    Engine-effective pair mismatch ``dbar = 0.5*sym - N*kappa - gamma*P0/3``
    (the pump self-phases at full gamma P0 while the sideband diagonals
    carry only (2/3) gamma P0; see ``probe_gain``). The legacy
    ``stmi_shift_thz`` used the +gamma_eff P0 bookkeeping and misses the
    root by +0.015-0.022 THz.
    """
    gamma_full = 2.0 * np.pi * N2 / LAMBDA0 / A_EFF
    tmp = gamma_full * P0_W / 3.0

    def f(om: float) -> float:
        sym = (
            beta0(PUMP_THZ + om) + beta0(PUMP_THZ - om) - 2.0 * beta0(PUMP_THZ)
        )
        return 0.5 * sym - n_ord * KAPPA - tmp

    xs = np.linspace(om_lo, om_hi, 60000)
    vals = np.array([f(x) for x in xs])
    idx = np.where(np.diff(np.sign(vals)) != 0)[0]
    if len(idx) == 0:
        raise RuntimeError(f"no corrected root for order {n_ord}")
    return float(brentq(f, xs[idx[0]], xs[idx[0] + 1]))


def check_b_deterministic(n_ord: int, L: float = 0.1, n_grid: int = 32768):
    """Deterministic check B' (ISSUES.md #10 tasks 6.1-6.3).

    Coherent conjugate-tone probe at the CORRECTED analytic root
    ``stmi_shift_thz_corrected``; asserts the measured exponent against the
    exact reduced 2x2 model:

        |b2|/a = sinh(g L), g = sqrt(c^2 - dbar^2),
        c = (2/3) gamma P0, dbar = 0.5 sym - N kappa - gamma P0/3,

    with an off-resonance control ~ 0 (no peak picking over a noise floor).
    Returns the metrics dict; raises AssertionError on failure.
    """
    global N_GRID
    old_n = N_GRID
    N_GRID = n_grid
    try:
        f_root = stmi_shift_thz_corrected(n_ord)
        f_off = f_root + 20.0
        res = probe_gain(n_ord, f_thz=f_root, L=L)
        res_off = probe_gain(n_ord, f_thz=f_off, L=L)
        c = (2.0 / 3.0) * (2.0 * np.pi * N2 / LAMBDA0 / A_EFF) * P0_W
        g = c  # dbar = 0 exactly at the corrected root
        b2_analytic = float(np.sinh(g * L))
        b2_meas = float(res["cols_a1"][1])
        err = abs(b2_meas - b2_analytic) / b2_analytic
        b2_off = float(res_off["cols_a1"][1])
        assert err < 0.20, (
            f"check B' growth mismatch: measured |b2|/a = {b2_meas:.4f}, "
            f"analytic sinh(gL) = {b2_analytic:.4f} ({err*100:.1f} %)"
        )
        assert b2_off < 0.05 * b2_meas, (
            f"off-resonance control not suppressed: |b2|/a = {b2_off:.4f}"
        )
        return {
            "n_ord": n_ord,
            "L_m": L,
            "root_corrected_thz": round(f_root, 4),
            "root_legacy_thz": round(stmi_shift_thz(n_ord), 4),
            "b2_analytic": round(b2_analytic, 4),
            "b2_measured": round(b2_meas, 4),
            "rel_err_pct": round(100.0 * err, 2),
            "b2_offresonance": round(b2_off, 4),
            "energy_drift_pct": float(res["energy_drift_pct"]),
        }
    finally:
        N_GRID = old_n

def stmi_shift_thz(n_ord: int) -> float:
    """Positive phase-matched detuning |Omega| (THz) for ladder order N."""

    def f(om: float) -> float:
        return delta_kappa(om, n_ord)

    xs = np.linspace(1.0, 270.0, 6000)
    vals = np.array([f(x) for x in xs])
    idx = np.where(np.diff(np.sign(vals)) != 0)[0]
    if len(idx) == 0:
        raise RuntimeError(f"no phase-matched root for order {n_ord}")
    return float(brentq(f, xs[idx[0]], xs[idx[0] + 1]))


def mi_gain_analytic(om_thz_grid: NDArray, n_ord: int) -> NDArray:
    """g(Omega) = sqrt((gamma_f P0)^2 - Delta(Omega)^2), 1/m."""
    gf = gamma_eff() * P0_W
    dk = np.array([delta_kappa(float(o), n_ord) for o in om_thz_grid])
    return np.sqrt(np.clip(gf**2 - dk**2, 0.0, None))


# ---------------------------------------------------------------------------
# engine runs
# ---------------------------------------------------------------------------


def betas_taylor(orders: int = 4) -> list[float]:
    """Even-order pair-sum dispersion of fused silica at 532 nm (SI list).

    The pair resonance depends on the symmetric sum ``sym(Omega) = beta0(w0+O)
    + beta0(w0-O) - 2 beta0(w0)``, in which every odd dispersion order cancels
    exactly; the engine therefore only needs the even orders (odd coefficients
    passed as 0.0).  The even coefficients are extracted by least squares on
    ``sym_real(Omega)`` against the scaled basis ``(Omega/Omega_max)^(2m)``
    (plain lstsq on unscaled powers is numerically hopeless here), over
    60-200 THz, then inverted from
    ``sym(O) = sum_m 2*beta_{2m}/(2m)! * O^(2m)`` (Omega in rad/ps).

    Returns a flat engine-ready list ``[beta2, 0, beta4, 0, beta6, 0,
    beta8, 0]`` (SI, s^k/m).  The engine must be fed this: a beta2-only
    engine misses the beta4+ pieces of the pair sum, which at these
    detunings contribute O(30) rad/m - larger than the whole gain band
    (+-6.27 rad/m).  Root cause of the failed check B of the earlier
    session.
    """
    f_grid = np.linspace(60.0, 200.0, 14)          # THz; covers all assert roots
    om = 2.0 * np.pi * f_grid                      # rad/ps
    sym_vals = np.array([
        beta0(PUMP_THZ + f) + beta0(PUMP_THZ - f) - 2.0 * beta0(PUMP_THZ)
        for f in f_grid
    ])
    om_max = float(om[-1])
    om_n = om / om_max
    cols = np.power.outer(om_n, 2.0 * np.arange(1, orders + 1))
    coefs, *_ = np.linalg.lstsq(cols, sym_vals, rcond=None)
    out: list[float] = []
    for m, a_m in enumerate(coefs, start=1):
        k = 2 * m
        beta_ps = a_m / om_max**k * factorial(k) / 2.0   # ps^k/m
        out.append(float(beta_ps / 1e12**k))             # s^k/m
        out.append(0.0)                                  # odd order (cancels)
    return out


def build_engine(
    *, n_ord: int, length_m: float, step_m: float, noise_rms: float = 1e-6
) -> MultimodeSplitStepEngine:
    """Pump (ch0, CW) + noise-seeded degenerate sideband pair (ch1, ch2).

    phase_offsets = [0, -N kappa, -N kappa] injects the GRIN modal-ladder
    phase of the sideband mode group N; betas shared (silica beta2 at
    532 nm); coef_model lp_degenerate (SPM 1, XPM 2/3, FWM 2/3).
    """
    grid = TemporalGrid(N=N_GRID, Tmax=Time(WINDOW_PS * 1e-12, "s"))
    a_pump = float(np.sqrt(P0_W))
    rng = np.random.default_rng(90210 + n_ord)
    waves: list[Wave] = []
    for ch in range(N_MODES):
        wave = Wave(
            grid=grid,
            envelope=Envelope(
                shape="gaussian",
                peak_amplitude=a_pump if ch == 0 else noise_rms * a_pump,
                pulse_width=Time(WINDOW_PS * 1e-12 / 4.0, "s"),
            ),
            central_wavelength=Wavelength(LAMBDA0_NM, "nm"),
        )
        if ch == 0:
            field = np.full(N_GRID, a_pump, dtype=complex)
        else:
            sig = noise_rms * a_pump / np.sqrt(2.0)
            field = rng.normal(0.0, sig, N_GRID) + 1j * rng.normal(
                0.0, sig, N_GRID
            )
        wave = wave.with_field(field)
        waves.append(wave)

    fiber = FiberProfile(
        n2=N2, alpha=0.0, A_eff=Area(A_EFF, "m^2"), length=Length(length_m, "m")
    )
    return MultimodeSplitStepEngine(
        waves,
        fiber,
        betas=[BETAS_FLAT] * N_MODES,
        betas_unit="s^k/m",
        phase_offsets=[0.0, float(-n_ord * KAPPA), float(-n_ord * KAPPA)],
        oam_l=[0, 0, 0],
        coef_model="lp_degenerate",
        include_fwm=True,
        fwm_pump_depletion=True,
        step_size=Length(step_m, "m"),
    )


BETAS_FLAT = betas_taylor()
PROBE_RMS = 1e-5  # coherent probe tone amplitude / pump amplitude


def probe_gain(n_ord: int, f_thz: float | None = None, L: float = 0.5) -> dict:
    """Deterministic engine-side parametric-gain probe (check B').

    Propagates a CW pump plus a coherent conjugate tone pair (a1 at +Om in
    ch1, a2 at -Om in ch2, each gPROBE_RMS * pump amplitude) through the
    engine and reads back the time-domain projection amplitudes of the two
    sideband channels.  Reference: the exact reduced 2x2 model

        |b1(L)|/|b1(0)| = cosh(g L),   |b2(L)|/|b1(0)| = sinh(g L),

    with g = sqrt(c^2 - dbar^2) and
        dbar = 0.5*sym(Omega) - N*kappa - (gamma P0)/3,
    c = (2/3) gamma P0 (FWM creation coupling), gamma the full Kerr
    coefficient; dbar is the engine's effective pair mismatch (the corrected
    Kerr term of ISSUES.md #10 - the pump self-phases at full gamma P0 while
    the sideband XPM diagonals carry only (2/3) gamma P0).
    """
    if f_thz is None:
        f_thz = stmi_shift_thz(n_ord)
    om = 2.0 * np.pi * f_thz * 1e12
    half_steps = int(round(L / STEP_M_LADDER))
    dz = L / half_steps
    grid = TemporalGrid(N=N_GRID, Tmax=Time(WINDOW_PS * 1e-12, "s"))
    tt = grid.t.as_s if hasattr(grid.t, "as_s") else grid.t
    tone = np.exp(1j * om * tt)
    a_sig = PROBE_RMS * float(np.sqrt(P0_W))

    def one_run(seed: tuple[float, float]) -> tuple[float, float]:
        """Seed (a1 tone weight, a2 tone weight); return output amplitudes."""
        waves: list[Wave] = []
        for ch in range(N_MODES):
            ww = Wave(
                grid=grid,
                envelope=Envelope(
                    shape="gaussian",
                    peak_amplitude=float(np.sqrt(P0_W)),
                    pulse_width=Time(WINDOW_PS * 1e-12 / 4.0, "s"),
                ),
                central_wavelength=Wavelength(LAMBDA0_NM, "nm"),
            )
            if ch == 0:
                field = np.full(N_GRID, float(np.sqrt(P0_W)), dtype=complex)
            elif ch == 1:
                field = a_sig * seed[0] * tone
            else:
                field = a_sig * seed[1] * np.conj(tone)
            waves.append(ww.with_field(np.asarray(field, complex)))
        fiber = FiberProfile(
            n2=N2, alpha=0.0, A_eff=Area(A_EFF, "m^2"), length=Length(L, "m")
        )
        eng = MultimodeSplitStepEngine(
            waves,
            fiber,
            betas=[BETAS_FLAT] * N_MODES,
            betas_unit="s^k/m",
            phase_offsets=[0.0, float(-n_ord * KAPPA), float(-n_ord * KAPPA)],
            oam_l=[0, 0, 0],
            coef_model="lp_degenerate",
            include_fwm=True,
            fwm_pump_depletion=True,
            step_size=Length(dz, "m"),
        )
        eng.propagate(half_steps, nsaves=2)
        a1_abs, a2_abs = A_proj(eng, grid, tone)
        drift = float(100.0 * abs(
            eng.energy_vs_z[-1] / eng.energy_vs_z[0] - 1.0))
        return a1_abs / a_sig, a2_abs / a_sig, drift

    def A_proj(eng, grid, tone):
        a1 = float(np.abs(np.asarray(eng.A[1], complex) @ np.conj(tone)) / N_GRID)
        a2 = float(
            np.abs(np.asarray(eng.A[2], complex) @ np.conj(np.conj(tone))) / N_GRID
        )
        return a1, a2

    proj1 = one_run((1.0, 0.0))   # seed a1 tone only
    proj2 = one_run((0.0, 1.0))   # seed a2 tone only
    _drift_pct = max(proj1[2], proj2[2])
    proj1, proj2 = proj1[:2], proj2[:2]
    return {
        "f_thz": float(f_thz),
        "L_m": L,
        "cols_a1": proj1,          # (|b1 out|/a_sig, |b2 out|/a_sig)
        "cols_a2": proj2,
        "energy_drift_pct": float(_drift_pct),
    }


def run_order(n_ord: int) -> tuple[MultimodeSplitStepEngine, dict]:
    """Propagate and return (engine, metrics)."""
    if n_ord == 0:
        step_m, num_steps = STEP_M_BASE, NUM_STEPS_BASE
    else:
        step_m, num_steps = STEP_M_LADDER, NUM_STEPS_LADDER
    eng = build_engine(
        n_ord=n_ord, length_m=step_m * num_steps, step_m=step_m
    )
    spec0 = np.abs(eng.grid.fft(np.asarray(eng.A[1], dtype=complex))) ** 2
    eng.propagate(num_steps, nsaves=min(num_steps, 33))
    freq_thz = np.abs(eng.grid.w) / (2.0 * np.pi * 1e12)
    spec1 = np.abs(eng.grid.fft(np.asarray(eng.A[1], dtype=complex))) ** 2
    spec2 = np.abs(eng.grid.fft(np.asarray(eng.A[2], dtype=complex))) ** 2
    energy = eng.energy_vs_z
    drift = float(abs(energy[-1] / energy[0] - 1.0))
    return eng, {
        "freq_thz": freq_thz,
        "spec1": spec1 * 0.0 + spec1,  # keep intensity only
        "spec2": spec2 * 0.0 + spec2,
        "spec1_init_abs": spec0.copy(),
        "energy_drift": drift,
    }


def sideband_peak_thz(
    freq_thz: NDArray, spec: NDArray, lo: float = 0.5, hi: float | None = None
) -> tuple[float, float]:
    """Spectral peak of one sideband half-plane within (lo, hi) THz."""
    if hi is None:
        hi = 260.0
    mask = (freq_thz > lo) & (freq_thz < hi)
    if mask.sum() < 8:
        raise RuntimeError("sideband search window too narrow")
    i = int(np.argmax(spec[mask]))
    return float(freq_thz[mask][i]), float(spec[mask][i])


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------


def validate(*, fast: bool = False, make_plot: bool = True) -> dict:
    """Validate the STMI reproduction.

    ``fast=True`` runs the deterministic check B' (ISSUES.md #10 resolution)
    at the corrected analytic root with a reduced probe length/grid instead
    of the full noise-seeded ladder runs (65536 grid x 25000 steps, ~hours):
    the banded readout assertion of check A is unchanged, check B is
    superseded by the coherent eigenvector probe.
    """
    params = json.loads(PARAMETERS.read_text())
    results: dict = {"parameters": params}

    if fast:
        # Deterministic check B' at the corrected root (short-L smoke):
        # assert growth vs sinh(gL) within 20%, off-resonance suppressed.
        probe = check_b_deterministic(2, L=0.15, n_grid=32768)
        results["check_b_deterministic"] = probe
        return results

    # --- analytic backbone ---------------------------------------------------
    beta2 = beta2_silica(LAMBDA0_NM)
    fs2_per_mm = beta2 * 1e27  # s^2/m -> fs^2/mm
    results["beta2_silica_532nm_fs2_per_mm"] = float(fs2_per_mm)
    assert 40.0 < fs2_per_mm < 100.0, fs2_per_mm  # strongly normal regime
    results["kappa_rad_per_m"] = round(KAPPA, 2)
    gamma_full = 2.0 * np.pi * N2 / LAMBDA0 / A_EFF
    results["gamma_per_W_m"] = float(gamma_full)
    results["gamma_eff_P0"] = float(gamma_eff() * P0_W)

    orders = sorted(PAPER_CIRCLES)
    roots = {n: stmi_shift_thz(n) for n in orders}
    results["analytic_roots_thz"] = {n: round(v, 2) for n, v in roots.items()}
    errs = {
        n: abs(roots[n] - PAPER_CIRCLES[n]) / PAPER_CIRCLES[n]
        for n in orders
        if n != 1
    }
    results["errors_vs_paper_pct"] = {n: round(e * 100, 2) for n, e in errs.items()}
    assert max(errs.values()) < 0.15, errs
    results["order1_stokes_residual_thz"] = float(
        roots[1] - PAPER_CIRCLES[1]
    )

    # --- engine ---------------------------------------------------------------
    numeric = {}
    runs = {}
    for n_ord in (1, 2):
        eng, m1 = run_order(n_ord)
        om_analytic_thz = stmi_shift_thz(n_ord)
        peak_thz, peak_power = sideband_peak_thz(
            m1["freq_thz"], m1["spec1"], lo=0.5, hi=1.8 * om_analytic_thz
        )
        rel = abs(peak_thz - om_analytic_thz) / om_analytic_thz
        # gain: the peak sideband bin at output vs the same bin at input
        k_peak = int(np.argmin(np.abs(m1["freq_thz"] - peak_thz)))
        e_in = float(m1["spec1_init_abs"][k_peak])
        e_out = float(m1["spec1"][k_peak])
        peak_gain = e_out / max(e_in, 1e-60)
        numeric[n_ord] = {
            "analytic_thz": round(om_analytic_thz, 3),
            "engine_peak_thz": round(peak_thz, 3),
            "rel_err_pct": round(100.0 * rel, 3),
            "peak_bin_gain": round(peak_gain, 1),
            "energy_drift_pct": round(100.0 * m1["energy_drift"], 3),
        }
        assert rel < 0.03, numeric[n_ord]
        assert peak_gain > 20.0, numeric[n_ord]
        assert m1["energy_drift"] < 0.02, m1["energy_drift"]
        runs[n_ord] = (eng, m1)

    results["engine_numeric"] = {str(k): v for k, v in numeric.items()}

    if make_plot:
        _make_fig(results, roots, runs)

    return results


def _band_energy(spec, freq_thz, window) -> float:
    mask = (freq_thz > window[0]) & (freq_thz < window[1])
    return float(np.sum(spec[mask]))


PAPER_SHIFT_SIGN = {5: -1, 4: -1, 2: +1, 1: +1}


def _make_fig(results, roots, runs) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.2))
    # (a) shift vs order: analytic branch + paper circles
    ax = axes[0]
    ns = np.arange(0.3, 6.3, 0.05)
    om = np.array([stmi_shift_thz(n) for n in ns])
    ax.plot(ns, om, "b-", label="this work (analytic ladder)")
    ax.plot(ns, -om, "b--")
    _px = [n for n in roots if n != 1]
    ax.plot([5, 4], [-188, -165], "o", ms=9, mfc="none", color="k", label="paper Fig. 3d")
    ax.plot([2, 1], [110, 65], "o", ms=9, mfc="none", color="k")
    ax.plot([-1], [PAPER_STOKES_ORDER1_THZ], "s", ms=8, mfc="none", color="r",
            label="paper Stokes-pump point (not on ladder)")
    ax.axhline(0, color="0.8", lw=0.5)
    ax.set_xlabel("ladder order N (paper MI order)")
    ax.set_ylabel("sideband shift (THz)")
    ax.set_title("(a) STMI sideband phase matching")
    ax.legend(fontsize=8)

    # (b) engine spectrum, order 2
    ax = axes[1]
    eng, m1 = runs[2]
    f = m1["freq_thz"]
    s = np.asarray(m1["spec1"])
    ok = (f >= 0) & (f <= 261)
    ax.plot(f[ok], s[ok], lw=0.7)
    ax.axvline(roots[2], color="r", ls="--", lw=1.0, label="analytic root")
    ax.axvline(PAPER_CIRCLES[2], color="k", ls=":", lw=1.0, label="paper circle")
    ax.set_yscale("log")
    ax.set_xlabel("shift (THz)")
    ax.set_ylabel("spectral intensity (norm.)")
    ax.set_title(f"(b) engine sideband order 2 (peak at {numeric_peak(runs,2)} THz)")
    ax.legend(fontsize=8)

    # (c) engine spectrum, order 1
    ax = axes[2]
    eng, m1 = runs[1]
    f = m1["freq_thz"]
    s = np.asarray(m1["spec1"])
    ok = (f >= 0) & (f <= 130)
    ax.plot(f[ok], s[ok], lw=0.7)
    ax.axvline(roots[1], color="r", ls="--", lw=1.0, label="analytic root")
    ax.axvline(PAPER_CIRCLES[1], color="k", ls=":", lw=1.0, label="paper circle")
    ax.set_yscale("log")
    ax.set_xlabel("shift (THz)")
    ax.set_title(f"(c) engine sideband order 1 (peak at {numeric_peak(runs,1)} THz)")
    fig.suptitle(
        "Wright et al. 2015 — STMI sideband phase matching (fibre a=13 um, Delta=0.0064, 532 nm)"
    )
    fig.tight_layout()
    out = HERE / "wright_2015_stmi.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)


def numeric_peak(runs, n_ord) -> str:
    eng, m1 = runs[n_ord]
    peak, _ = sideband_peak_thz(m1["freq_thz"], m1["spec1"], lo=0.5, hi=None)
    return f"{peak:.1f}"


if __name__ == "__main__":
    out = validate()
    print(json.dumps(out, indent=2, default=float))
