#!/usr/bin/env python3
"""Reproduce the Schrodinger-example PINN of Raissi, Perdikaris & Karniadakis,
"Physics-informed neural networks: A deep learning framework for solving
forward and inverse problems involving nonlinear PDEs", J. Comput. Phys. 378,
686 (2019), doi:10.1016/j.jcp.2018.10.045 — with the ground-truth data
generated by photonics_helper instead of Chebfun.

The article (Sec. 2.2)
----------------------
The continuous-time PINN is applied to the periodic focusing NLSE

    i h_t + 0.5 h_xx + |h|^2 h = 0,   x in [-5, 5],  t in [0, pi/2],
    h(0, x) = 2 sech(x),              h(t, -5) = h(t, 5),  h_x(t, -5) = h_x(t, 5).

h(0, x) = 2 sech(x) is the N = 2 soliton (N^2 = gamma P0 T0^2 / |beta2| = 4 in
the units below), so the window t in [0, pi/2] is exactly one breather
period.  The paper generates the reference with Chebfun (256 Fourier modes,
RK4, dt = pi/2 * 1e-6), keeps N0 = 50 points of h(0, x) on the initial line,
Nb = 50 random boundary pairs {t, x = +-5} and Nf = 20000 interior collocation
points (Latin Hypercube), represents h(t, x) = [u, v] with a 5-layer, 100-neuron
tanh network, and minimizes MSE = MSE0 + MSE_b + MSE_f with

    f = i h_t + 0.5 h_xx + |h|^2 h

evaluated by automatic differentiation.  Reported relative L2 error: 1.97e-3.

Unit mapping (engine <-> paper)
-------------------------------
A(z, T) = A0 * h(t, x) with T = T_s x, z = L_s t turns the paper PDE into the
engine's Agrawal-form equation A_z = -i (beta2/2) A_TT + i gamma |A|^2 A with

    beta2 = -T_s^2 / L_s,      gamma = 1 / (L_s A0^2).

Chosen T_s = 1 ps, L_s = 1 m, A0 = 1 W: beta2 = -1 ps^2/m, gamma = 1 W^-1 m^-1,
peak power 2 W, T0 = 1 ps, span pi/2 m.  (Dimensionless physics; the carrier
wavelength only feeds the unused omega0.)

Checks
------
1. Engine data generation is validated BEFORE any PINN work:
   1a. fundamental-soliton sector: A = sech(T/T0) e^{i z/2} reproduced by the
       engine at z = pi/4 (analytic closed form, machine-precision target);
   1b. independent RK4IP integrator (written here, finer step) vs the engine
       on the N = 2 problem (relative L2 on the final field);
   1c. breather recurrence at z = pi/2: |h| returns to 2 sech(x);
   1d. energy conservation of the engine run.
2. PINN training (torch, float64, fixed seeds): relative L2 against the paper's
   1.97e-3 (accept <= 5e-3), cut profiles at t = 0.59, 0.79, 0.98, MSE0/MSE_b/
   MSE_f history.
3. Stretch: learnable lambda in f = i h_t + 0.5 h_xx + lambda |h|^2 h, init 0.5,
   recovered from the same data (paper's "lambda = 1" inverse direction).

Usage
-----
    python reproductions/planned/raissi_2019_pinn_nlse/reproduce.py
"""

from __future__ import annotations

import json
import math
import os
import time
from pathlib import Path

import numpy as np
from tqdm import tqdm

from photonics_helper.base import C_MS, Length, Time, Wavelength
from photonics_helper.gnlse import FiberProfile, GNLSESolver
from photonics_helper.pulse import Envelope, TemporalGrid, Wave

HERE = Path(__file__).resolve().parent
PARAMETERS = HERE / "parameters.json"


# ---------------------------------------------------------------------------
# data generation (photonics_helper SplitStep engine)
# ---------------------------------------------------------------------------

def _sech(x):
    return 1.0 / np.cosh(x)


def _make_pulse(grid: TemporalGrid, params: dict, peak_W: float,
                T0_ps: float) -> Wave:
    """Custom sech envelope with the given field peak (2 W -> N = 2, 1 W -> N = 1)."""
    env = Envelope(
        shape="custom",
        peak_amplitude=peak_W,
        pulse_width=Time(T0_ps * 1e-12, "s"),
        func=lambda t, T0, A0: A0 * _sech(t / T0),
    )
    lam = params["engine_mapping"]["central_wavelength_nm"]
    return Wave(
        grid=grid,
        envelope=env,
        central_wavelength=Wavelength(lam, "nm"),
    )


def _run_engine(params: dict, *, fundamental: bool = False,
                num_steps: int | None = None) -> tuple[TemporalGrid, np.ndarray, np.ndarray]:
    """Propagate with the engine; return (grid, z_array, H[nz, nx] complex).

    ``fundamental=True`` runs the N = 1 soliton (peak 1 W) to z = pi/4 for
    check 1a; otherwise the paper's N = 2 problem over [0, pi/2].
    """
    g = params["grid"]
    em = params["engine_mapping"]
    grid = TemporalGrid(N=g["N"], Tmax=Time(g["Tmax_ps"] * 1e-12, "s"))
    if fundamental:
        peak, z_span = 1.0, math.pi / 4.0
    else:
        peak, z_span = em["peak_power_W"], em["z_span_m"]
    pulse = _make_pulse(grid, params, peak, em["T0_ps"])
    fiber = FiberProfile.from_gamma(
        gamma=em["gamma_per_W_m"],
        n2=2.6e-20,
        omega0=2 * np.pi * C_MS / (em["central_wavelength_nm"] * 1e-9),
        length=Length(z_span, "m"),
    )
    solver = GNLSESolver(
        pulse=pulse,
        fiber=fiber,
        betas=np.array([em["beta2_ps2_per_m"]]),
        include_raman=False,
        include_self_steepening=False,
        include_tpa=False,
    )
    steps = num_steps or g["num_steps"]
    solver.propagate(steps, nsaves=2 if fundamental else g["n_snapshots"])
    H = np.array([w.envelope_field for w in solver.evolution])
    return grid, np.asarray(solver.z_array), H


def analytic_fundamental(t_s: np.ndarray, z: float, T0_s: float) -> np.ndarray:
    """N = 1 soliton of A_z = i(|beta2|/2) A_TT + i gamma |A|^2 A with
    |beta2| = gamma = T0 = 1 (engine units): A = sech(T/T0) e^{i z/2}."""
    return _sech(t_s / T0_s) * np.exp(1j * z / 2.0)


def _rk4ip_reference(grid: TemporalGrid, A0: np.ndarray, z_span: float,
                     n_steps: int, *, T_s: float = 1e-12,
                     L_s: float = 1.0) -> np.ndarray:
    """Independent RK4IP split-step integrator (Hult 2007) for
    A_z = i(0.5 A_TT + |A|^2 A) on the engine's grid; cross-check 1b."""
    # linear multiplier of A_z = -i(beta2/2) A_TT + i gamma |A|^2 A:
    # A_TT -> -w^2 under the FFT pair, so D(w) = +i beta2 w^2 / 2
    # (beta2 < 0 makes D negative-imaginary in w: focusing).
    w = 2 * np.pi * np.fft.fftfreq(len(A0), d=grid.dt)
    beta2_si = -(T_s**2) / L_s  # s^2/m (negative, focusing)
    D = 0.5j * beta2_si * w**2

    def N(a):
        return 1j * np.abs(a) ** 2 * a

    def L(a, h):
        return np.fft.ifft(np.exp(D * h) * np.fft.fft(a))

    dz = z_span / n_steps
    A = A0.copy()
    for _ in tqdm(range(n_steps), desc="rk4ip-cross-check", leave=False,
                  unit="step"):
        Ah = L(A, dz / 2)
        k1 = N(Ah)
        k2 = N(L(Ah + dz / 2 * k1, dz / 2))
        k3 = N(L(Ah + dz / 2 * k2, dz / 2))
        k4 = N(L(Ah + dz * k3, dz))
        A = L(Ah + dz / 6 * (k1 + 2 * k2 + 2 * k3 + k4), dz / 2)
    return A


def rel_l2(err: np.ndarray, ref: np.ndarray) -> float:
    return float(np.linalg.norm(err) / np.linalg.norm(ref))


def validate_data(params: dict) -> dict:
    """Checks 1a-1d: the engine data is trustworthy before PINN training."""
    g = params["grid"]
    tol = params["validation_tolerances"]
    out: dict = {}

    # 1a — fundamental-soliton sector vs the closed form
    grid, z_arr, H1 = _run_engine(params, fundamental=True, num_steps=40000)
    A_exact = analytic_fundamental(grid.t, float(z_arr[-1]), 1e-12)
    out["fundamental_z_over_pi"] = float(z_arr[-1] / math.pi)
    out["fundamental_max_abs_err"] = float(np.max(np.abs(H1[-1] - A_exact)))
    out["fundamental_rel_l2"] = rel_l2(H1[-1] - A_exact, A_exact)

    # 1b/1c/1d — the paper's N = 2 problem
    grid, z_arr, H = _run_engine(params)
    t_s = grid.t
    x = t_s / 1e-12

    # 1b: independent RK4IP at 4x steps, same grid
    em = params["engine_mapping"]
    A_ref = _rk4ip_reference(
        grid, H[0], float(em["z_span_m"]), 4 * g["num_steps"],
        T_s=em["T_s_ps"] * 1e-12, L_s=em["L_s_m"])
    out["cross_check_rel_l2_final"] = rel_l2(H[-1] - A_ref, A_ref)
    z_mid = float(z_arr[len(z_arr) // 2])
    A_ref_mid = _rk4ip_reference(
        grid, H[0], z_mid, max(1, 2 * g["num_steps"]),
        T_s=em["T_s_ps"] * 1e-12, L_s=em["L_s_m"])
    out["cross_check_rel_l2_mid"] = rel_l2(H[len(z_arr) // 2] - A_ref_mid,
                                           A_ref_mid)

    # 1c: breather recurrence at z = pi/2
    out["recurrence_rel_l2"] = rel_l2(np.abs(H[-1]) - 2.0 * _sech(x),
                                      2.0 * _sech(x))

    # 1d: energy (photon-number analog) conservation
    energies = np.array([np.sum(np.abs(h) ** 2) for h in H])
    out["energy_drift"] = float(np.max(np.abs(energies / energies[0] - 1.0)))

    assert out["fundamental_max_abs_err"] < tol["fundamental_soliton_max_abs_err"], out
    assert out["cross_check_rel_l2_final"] < tol["cross_check_rel_l2"], out
    assert out["cross_check_rel_l2_mid"] < tol["cross_check_rel_l2_mid"], out
    assert out["recurrence_rel_l2"] < tol["recurrence_rel_l2"], out
    assert out["energy_drift"] < tol["data_energy_drift"], out
    return out


# ---------------------------------------------------------------------------
# PINN (torch, float64)
# ---------------------------------------------------------------------------

def _torch():
    try:
        # Pre-import allocator settings for GPU runs (ignored on CPU): keep the
        # caching allocator from hoarding GPU memory with tall autograd graphs.
        os.environ.setdefault(
            "PYTORCH_ALLOC_CONF",
            "expandable_segments:True,garbage_collection_threshold:0.9")
        import torch
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "The Raissi-2019 reproduction requires torch: pip install torch"
        ) from exc
    return torch


def _gpu_guardrails(torch, device: str) -> str:
    """Fails-safe GPU setup. Returns the device to actually use.

    Guardrails for the amdgpu/ROCm path that crashed the machine before:

    1. cap the caching allocator at PH_GPU_CAP_FRAC (default 0.6) of the
       GPU memory — an integrated GPU shares system RAM, so an uncapped
       allocator can take the desktop down;
    2. forced empty_cache every 200 training iterations in the training loop;
    3. callers catch torch.cuda.OutOfMemoryError and fall back to cpu.
    """
    if device == "cpu":
        return "cpu"
    if not torch.cuda.is_available():
        print("  [guardrail] no GPU backend available -> fallback cpu")
        return "cpu"
    props = torch.cuda.get_device_properties(0)
    cap = float(os.environ.get("PH_GPU_CAP_FRAC", "0.6"))
    try:
        torch.cuda.set_per_process_memory_fraction(cap, 0)
        capped_msg = (f"allocator capped at {cap:.0%} of "
                      f"{props.total_memory/2**30:.1f} GiB")
    except Exception as exc:
        capped_msg = f"allocator cap not supported ({exc})"
    print(f"  [guardrail] GPU: {props.name}; {capped_msg}; "
          "empty_cache every 200 iters; OOM -> cpu fallback")
    return device


def train_pinn(params: dict, H: np.ndarray, z_arr: np.ndarray, *,
               discover_lambda: bool = False, fast: bool = False,
               seed: int | None = None, verbose: bool = False,
               device: str = "cpu", nf_chunk: int = 0,
               adam_iters: int | None = None,
               resume: bool = False) -> dict:
    """Train the continuous-time PINN; returns metrics + the trained model."""
    torch = _torch()
    from scipy.stats import qmc

    p = params["pinn"]
    em = params["engine_mapping"]
    seed = p["seed"] if seed is None else seed
    # Compute device: the ROCm build on the amdgpu iGPU crashed the system
    # during training (shared-memory float64 autograd spike), so the safe
    # default is "cpu". Options (env var or --device CLI flag):
    #   cpu   — safe, slowest (recommended on this box)
    #   cuda  — GPU with guardrails (memory cap, periodic empty_cache,
    #           automatic fallback to cpu on OOM); covers the CUDA build on
    #           NVIDIA or the ROCm build on AMD (a "vulkan" training backend
    #           does not exist in torch)
    #   auto  — cuda if available, else cpu
    torch = _torch()
    device = (os.environ.get("PH_PINN_DEVICE", "cpu") if device == "cpu"
              else device).strip().lower()
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    device = _gpu_guardrails(torch, device)
    print(f"  [device] training on: {device} "
          f"(torch {torch.__version__}; override with PH_PINN_DEVICE/--device)")
    dtype = torch.float64
    torch.manual_seed(seed)
    np.random.seed(seed)

    layers, width = (2, 32) if fast else (p["layers"], p["width"])
    adam_iters = 300 if fast else (adam_iters or p["adam_iters"])
    lbfgs_iters = 0 if fast else p["lbfgs_max_iter"]
    n0, nb, nf = (20, 20, 2000) if fast else (p["N0"], p["Nb"], p["Nf"])

    t_min, t_max = 0.0, float(em["z_span_m"])          # t in meters (z = L_s t)
    x_min, x_max = params["pde"]["x_domain"]
    # normalization: inputs mapped to [-1, 1]
    t_c, t_h = 0.5 * (t_max + t_min), 0.5 * (t_max - t_min)
    x_c, x_h = 0.5 * (x_max + x_min), 0.5 * (x_max - x_min)

    # network: (tn, xn) -> (u, v); tn, xn in [-1, 1]
    mods: list = []
    din = 2
    for _ in range(layers):
        lin = torch.nn.Linear(din, width, dtype=dtype)
        torch.nn.init.xavier_normal_(lin.weight)
        mods += [lin, torch.nn.Tanh()]
        din = width
    mods.append(torch.nn.Linear(din, 2, dtype=dtype))
    torch.nn.init.xavier_normal_(mods[-1].weight)
    net = torch.nn.Sequential(*mods).to(device)
    params_nn = list(net.parameters())

    lam = None
    if discover_lambda:
        lam = torch.tensor([p["lambda_discovery_init"]], dtype=dtype,
                           device=device, requires_grad=True)
        params_nn.append(lam)

    # ---- training data from the engine fields (H[nz, nx], t = z_arr) ----
    nz, nx = H.shape
    t_all = torch.tensor(z_arr, dtype=dtype)
    x_all = torch.tensor(np.arange(nx) * (2 * x_h * 1.0) / nx - x_h, dtype=dtype)
    h_all = torch.tensor(H, dtype=torch.complex128)  # [nz, nx]

    # N0: Latin hypercube of the initial line
    x0 = qmc.LatinHypercube(d=1, seed=seed).random(n0)[:, 0]
    x0 = x_min + (x_max - x_min) * x0
    h0 = torch.tensor(2.0 * _sech(x0), dtype=dtype)  # exact initial line

    # Nb: random pairs on the two boundaries
    tb = qmc.LatinHypercube(d=1, seed=seed + 1).random(nb)[:, 0]
    tb = t_min + (t_max - t_min) * tb

    # Nf: Latin hypercube over the full (t, x) rectangle
    q = qmc.LatinHypercube(d=2, seed=seed + 2).random(nf)
    tf = t_min + (t_max - t_min) * q[:, 0]
    xf = x_min + (x_max - x_min) * q[:, 1]

    def tens(a):
        return torch.tensor(np.asarray(a, dtype=float), dtype=dtype,
                            device=device).reshape(-1, 1)

    x0_t, h0_t = tens(x0), tens(h0)
    tb_t = tens(tb)
    tf_t, xf_t = tens(tf), tens(xf)

    def h_of(t, x):
        tn = (t - t_c) / t_h
        xn = (x - x_c) / x_h
        out = net(torch.cat([tn, xn], dim=1))
        return out[:, 0:1], out[:, 1:2]

    def residual(t, x):
        t = t.clone().requires_grad_(True)
        x = x.clone().requires_grad_(True)
        u, v = h_of(t, x)
        grads = []
        for y in (u, v):
            g_t = torch.autograd.grad(y, t, torch.ones_like(y), create_graph=True)[0]
            g_x = torch.autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
            g_xx = torch.autograd.grad(g_x, x, torch.ones_like(g_x),
                                       create_graph=True)[0]
            grads.append((g_t, g_xx))
        (u_t, u_xx), (v_t, v_xx) = grads
        n2 = u * u + v * v
        lam_ = lam if lam is not None else 1.0
        f_u = -v_t + 0.5 * u_xx + lam_ * n2 * u
        f_v = u_t + 0.5 * v_xx + lam_ * n2 * v
        return f_u, f_v

    def loss_fn(chunk_idx: torch.Tensor | None = None):
        # MSE0: initial line (u = 2 sech, v = 0)
        u0, v0 = h_of(torch.zeros_like(x0_t), x0_t)
        mse0 = ((u0 - h0_t) ** 2 + v0 ** 2).mean()
        # MSE_b: periodic h and h_x at x = +-5
        t1 = tb_t.clone().requires_grad_(True)
        xp1 = torch.full_like(t1, x_min).requires_grad_(True)
        xm1 = torch.full_like(t1, x_max).requires_grad_(True)
        up, vp = h_of(t1, xp1)
        um, vm = h_of(t1, xm1)
        dxp = torch.autograd.grad(up.sum() + vp.sum(), xp1,
                                  create_graph=True)[0]
        dxm = torch.autograd.grad(um.sum() + vm.sum(), xm1,
                                  create_graph=True)[0]
        mse_b = ((up - um) ** 2 + (vp - vm) ** 2
                 + (dxp - dxm) ** 2).mean()
        # MSE_f (guardrail: optionally train on a rotating evaluation subset of
        # the collocation cloud — cuts autograd-graph memory roughly by Nf/chunk,
        # needed to keep the amdgpu iGPU (shared system RAM) below its cap)
        if nf_chunk and nf_chunk < nf:
            # chunk_idx (fixed subset) is used by the LBFGS closure: a *stochastic*
            # closure poisons L-BFGS — the strong-Wolfe line search and the
            # |loss - prev_loss| < tolerance_change termination both assume a
            # deterministic objective, and noise makes torch's LBFGS bail out
            # after a handful of iterations (observed: exit at 13 closures,
            # rel-L2 0.21). Adam keeps the rotating subset.
            idx = (chunk_idx if chunk_idx is not None
                   else torch.randint(0, nf, (nf_chunk,), device=tf_t.device))
            xfc, xfc2 = tf_t[idx], xf_t[idx]
        else:
            xfc, xfc2 = tf_t, xf_t
        fu, fv = residual(xfc, xfc2)
        mse_f = (fu ** 2 + fv ** 2).mean()
        return mse0 + mse_b + mse_f

    opt = torch.optim.Adam(params_nn, lr=p["adam_lr"])
    hist = []
    t0 = time.time()
    start_iter = 0
    ckpt_path = HERE / "pinn_checkpoint.pt"
    if resume and ckpt_path.exists():
        ck = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
        stage = ck.get("stage", f"adam@{ck.get('adam_iter')}" if "adam_iter" in ck
                        else "lbfgs-mid")
        sd = ck["net"].state_dict() if hasattr(ck["net"], "state_dict") else ck["net"]
        net.load_state_dict(sd)
        if lam is not None and "lam" in ck:
            lam.data.copy_(ck["lam"].to(device))
        if stage.startswith("adam"):
            if "opt" in ck:
                opt.load_state_dict({k: (v if not hasattr(v, "to") else
                                         {kk: (vv.to(device) if hasattr(vv, "to")
                                               else vv) for kk, vv in v.items()}
                                         if isinstance(v, dict) else v)
                                     for k, v in ck["opt"].items()})
            start_iter = int(ck["adam_iter"]) + 1
            hist = list(ck.get("hist", []))
            print(f"  [resume] Adam continued from iter {start_iter} "
                  f"(loss {ck.get('loss'):.3e}; optimizer state restored)")
        elif stage.startswith("lbfgs") or stage == "pre-eval-final":
            start_iter = adam_iters
            hist = list(ck.get("hist", []))
            print(f"  [resume] checkpoint stage '{stage}': weights loaded, "
                  "Adam skipped, LBFGS refinement starts")
        else:
            start_iter = 0
            print(f"  [resume] unrecognised stage '{stage}' -> full restart")
    elif resume:
        print(f"  [resume] no checkpoint at {ckpt_path} -> full restart")
    pbar = tqdm(range(start_iter, adam_iters), desc="Adam", unit="it",
                initial=0)
    for it in pbar:
        opt.zero_grad()
        loss = loss_fn()
        loss.backward()
        opt.step()
        hist.append(float(loss.detach()))
        if (it + 1) % max(1, adam_iters // 200) == 0:
            pbar.set_postfix({"loss": f"{hist[-1]:.3e}",
                              "s": int(time.time() - t0)})
        if device != "cpu" and (it + 1) % 200 == 0:
            torch.cuda.empty_cache()
        if (it + 1) % max(1, adam_iters // 200) == 0:
            pbar.set_postfix({"loss": f"{hist[-1]:.3e}",
                              "s": int(time.time() - t0)})
        if device != "cpu" and (it + 1) % 200 == 0:
            torch.cuda.empty_cache()
        # periodic checkpoint: an interrupt or a failed assert must never
        # destroy hours of trained weights (weights + Adam moments so that
        # --resume can also restore optimizer state)
        if (it + 1) % 2000 == 0:
            torch.save({"net": net, "opt": opt.state_dict(), "seed": seed,
                        "adam_iter": it, "adam_iters": adam_iters,
                        "stage": f"adam@{it}", "loss": hist[-1],
                        "hist": hist},
                       str(ckpt_path))
    pbar.close()
    if hist:
        # full Adam path ran (or resumed mid-Adam); overwrite the checkpoint
        # with the end-of-Adam state.  On a pure LBFGS/pre-eval resume the
        # checkpoint is already the trained net — do NOT clobber it.
        torch.save({"net": net, "opt": opt.state_dict(), "seed": seed,
                    "adam_iter": adam_iters - 1, "adam_iters": adam_iters,
                    "stage": f"adam@{adam_iters - 1}", "loss": hist[-1],
                    "hist": hist},
                   str(ckpt_path))
        pbar.close()
        print(f"  Adam done in {time.time() - t0:.0f}s, final loss {hist[-1]:.3e}")
    else:
        print("  Adam skipped (LBFGS/pre-eval resume): checkpoint net kept")

    if lbfgs_iters:
        pbar = tqdm(total=lbfgs_iters, desc="LBFGS", unit="iter")
        opt2 = torch.optim.LBFGS(params_nn, max_iter=lbfgs_iters,
                                 history_size=p["lbfgs_history"],
                                 tolerance_grad=1e-12, tolerance_change=1e-14,
                                 line_search_fn="strong_wolfe")
        count = [0]
        # one fixed collocation subset for the whole LBFGS phase -> the closure
        # is deterministic and the line search can actually descend
        lbfgs_idx = (torch.randint(0, nf, (nf_chunk,), device=tf_t.device)
                     if nf_chunk and nf_chunk < nf else None)

        def closure():
            opt2.zero_grad()
            loss = loss_fn(chunk_idx=lbfgs_idx)
            loss.backward()
            hist.append(float(loss.detach()))
            count[0] += 1
            pbar.update(1)
            pbar.set_postfix({"loss": f"{loss:.3e}",
                              "s": int(time.time() - t0)})
            # periodic checkpoint during LBFGS too (weights only; the LBFGS
            # history cannot be meaningfully frozen/cloned mid-refinement)
            if count[0] % 2000 == 0:
                torch.save({"net": net, "seed": seed,
                            "lbfgs_closures": count[0],
                            "loss": float(loss.detach()),
                            "stage": "lbfgs-mid"},
                           str(HERE / "pinn_checkpoint.pt"))
            return loss

        opt2.step(closure)
        pbar.close()
        print(f"  LBFGS done in {time.time() - t0:.0f}s, final loss {hist[-1]:.3e}")
        if device != "cpu":
            torch.cuda.empty_cache()

    metrics = {
        "device": device,
        "loss_final": hist[-1],
        "loss_history": hist,
        "train_seconds": time.time() - t0,
    }
    if lam is not None:
        metrics["lambda_recovered"] = float(lam.detach())
        metrics["lambda_error_pct"] = abs(float(lam.detach()) - 1.0) * 100.0
    # checkpoint the trained net BEFORE evaluation asserts can fire (guardrail:
    # a failed rel-L2 assert must not destroy hours of trained weights).
    # fast/smoke runs must NEVER clobber the real checkpoint (the 2x32 smoke
    # net once overwrote a finished 5x100 training — guard added 2026-09-22).
    import torch as _t
    ckpt = HERE / ("pinn_checkpoint_smoke.pt" if fast else "pinn_checkpoint.pt")
    state = {"net": net, "discover_lambda": discover_lambda,
             "seed": seed, "adam_iters": adam_iters,
             "loss_final": hist[-1],
             "stage": "pre-eval-final", "hist": hist}
    if lam is not None:
        state["lam"] = lam.detach().clone()
    _t.save(state, str(ckpt))
    print(f"  [checkpoint] trained net saved to {ckpt}")
    return {"metrics": metrics, "net": net, "h_of": h_of,
            "t_all": t_all, "x_all": x_all, "h_all": h_all}


def evaluate_pinn(trained: dict, H: np.ndarray, z_arr: np.ndarray) -> dict:
    """Relative L2 over the full grid + cut profiles (t = 0.59, 0.79, 0.98)."""
    torch = _torch()
    device = trained["metrics"]["device"]
    h_of, t_all, x_all = trained["h_of"], trained["t_all"], trained["x_all"]
    h_pred = np.zeros_like(H)
    xt = x_all.reshape(-1, 1).to(device)
    with torch.no_grad():
        for k in tqdm(range(t_all.shape[0]), desc="PINN-eval", leave=False,
                      unit="snap"):
            tk = torch.full_like(xt, float(t_all[k]))
            u, v = h_of(tk, xt)
            h_pred[k] = (u + 1j * v).cpu().numpy().reshape(-1)
    out = {"rel_l2_full": rel_l2(h_pred - H, H)}
    out["rel_l2_real"] = rel_l2(h_pred.real - H.real, H.real)
    out["rel_l2_imag"] = rel_l2(h_pred.imag - H.imag, H.imag)
    # cut profiles at the paper's instants (nearest snapshot; spacing pi/2/200)
    cuts = {}
    for tc in (0.59, 0.79, 0.98):
        k = int(np.argmin(np.abs(z_arr - tc)))
        cuts[str(tc)] = {
            "snapshot_t": float(z_arr[k]),
            "rel_l2": rel_l2(h_pred[k] - H[k], H[k]),
            "exact": H[k], "pred": h_pred[k],
        }
    out["cuts"] = cuts
    return out, h_pred


# ---------------------------------------------------------------------------
# figures
# ---------------------------------------------------------------------------

def _make_plots(H: np.ndarray, z_arr: np.ndarray, h_pred: np.ndarray,
                x0: np.ndarray, tb: np.ndarray, trained: dict,
                out_dir: Path) -> list[str]:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    x = np.linspace(-5.0, 5.0, H.shape[1])
    figs = []
    # Fig. 2 style: top |h| heatmap + data locations; bottom cuts
    fig, axes_all = plt.subplots(
        2, 3, figsize=(10, 6), gridspec_kw={"height_ratios": [1.4, 1]},
    )
    ax1, axes = axes_all[0, 0], axes_all[1]
    ax_re, ax_im = axes_all[0, 1], axes_all[0, 2]
    ext = [z_arr[0], z_arr[-1], x[0], x[-1]]
    im = ax1.imshow(np.abs(h_pred), extent=ext, origin="lower", aspect="auto",
                    cmap="viridis")
    ax1.scatter(np.zeros_like(x0), x0, s=6, c="k", marker="x",
                label=f"initial data (N0)")
    ax1.scatter(tb, np.full_like(tb, 5.0), s=6, c="k", marker="x")
    ax1.scatter(tb, np.full_like(tb, -5.0), s=6, c="k", marker="x")
    for tc in (0.59, 0.79, 0.98):
        ax1.axvline(tc, c="w", lw=0.8, alpha=0.8)
    ax1.set_xlabel("t"); ax1.set_ylabel("x")
    ax1.set_title("|h(t,x)| — PINN prediction + training data")
    fig.colorbar(im, ax=ax1)
    ax1.legend(loc="upper right", fontsize=7)
    # paper Fig. 2 layout: full row of predicted component heatmaps
    vmax = float(np.max(np.abs(h_pred.real))) or 1.0
    im_re = ax_re.imshow(h_pred.real, extent=ext, origin="lower",
                         aspect="auto", cmap="RdBu_r", vmin=-vmax, vmax=vmax)
    ax_re.set_xlabel("t"); ax_re.set_title("Re h — PINN prediction", fontsize=10)
    fig.colorbar(im_re, ax=ax_re)
    im_im = ax_im.imshow(h_pred.imag, extent=ext, origin="lower",
                         aspect="auto", cmap="RdBu_r",
                         vmin=-vmax, vmax=vmax)
    ax_im.set_xlabel("t"); ax_im.set_title("Im h — PINN prediction", fontsize=10)
    fig.colorbar(im_im, ax=ax_im)
    for ax, tc in zip(axes, (0.59, 0.79, 0.98)):
        c = trained["eval"]["cuts"][str(tc)]
        k = int(np.argmin(np.abs(z_arr - tc)))
        ax.plot(x, H[k].real, "b-", lw=1.4, label="exact (engine)")
        ax.plot(x, c["pred"].real, "r--", lw=1.2, label="PINN")
        ax.set_title(f"u: t = {tc} (snap {c['snapshot_t']:.3f})", fontsize=9)
        ax.set_xlabel("x")
    axes[0].set_ylabel("u")
    axes[0].legend(fontsize=7)
    fig.suptitle("Raissi 2019 Schrodinger PINN — photonics_helper data")
    fig.tight_layout()
    p = out_dir / "fig2_pinn_prediction.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    figs.append(p.name)

    # exact |h| reference heatmap
    fig, ax = plt.subplots(figsize=(7, 3.4))
    im = ax.imshow(np.abs(H), extent=ext, origin="lower", aspect="auto",
                   cmap="viridis")
    ax.set_xlabel("t"); ax.set_ylabel("x")
    ax.set_title("|h(t,x)| — exact (SplitStepEngine, N=2 breather)")
    fig.colorbar(im, ax=ax)
    fig.tight_layout()
    p = out_dir / "fig1_exact_breather.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    figs.append(p.name)

    # loss history
    hist = trained["metrics"]["loss_history"]
    fig, ax = plt.subplots(figsize=(5.5, 3.4))
    ax.semilogy(hist, lw=0.8)
    ax.set_xlabel("iteration"); ax.set_ylabel("MSE0 + MSE_b + MSE_f")
    ax.set_title("PINN training loss")
    fig.tight_layout()
    p = out_dir / "fig3_loss.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    figs.append(p.name)
    return figs


# ---------------------------------------------------------------------------
# validate (house contract)
# ---------------------------------------------------------------------------

def validate(*, make_plot: bool = True, fast: bool = False,
             discover_lambda: bool = False, verbose: bool = False,
             device: str = "cpu", nf_chunk: int = 0,
             adam_iters: int | None = None,
             resume: bool = False) -> dict:
    """Run every check and return the measured metrics (house contract).

    ``device`` pins the compute backend: "cpu" (safe default on this box),
    "cuda" (torch CUDA / ROCm build with the _gpu_guardrails caps + automatic
    OOM fallback to cpu) or "auto".  ``nf_chunk`` subsamples the collocation
    cloud per iteration (0 = paper-exact full batch; e.g. 5000 cuts the
    autograd graph to a quarter and keeps the iGPU under its memory cap).
    """
    torch = _torch()
    params = json.loads(PARAMETERS.read_text())
    results: dict = {"derived": {
        "note": "units: t in the PINN is z in meters (L_s = 1 m)",
        "N2_breather_period_m": math.pi / 2.0,
    }}
    results["data_validation"] = validate_data(params)

    grid, z_arr, H = _run_engine(params)
    # crop the engine window (+-10 ps) to the paper's domain x in [-5, 5]
    n_big = H.shape[1]
    H = H[:, n_big // 4: 3 * n_big // 4]
    try:
        trained = train_pinn(params, H, z_arr, discover_lambda=discover_lambda,
                             fast=fast, verbose=verbose, device=device,
                             nf_chunk=nf_chunk, adam_iters=adam_iters,
                             resume=resume)
    except torch.cuda.OutOfMemoryError:
        torch.cuda.empty_cache()
        print("  [guardrail] CUDA OOM hit -> empty_cache and FULL cpu fallback")
        trained = train_pinn(params, H, z_arr, discover_lambda=discover_lambda,
                             fast=fast, verbose=verbose, device="cpu",
                             nf_chunk=nf_chunk, adam_iters=adam_iters,
                             resume=resume)
    ev, h_pred = evaluate_pinn(trained, H, z_arr)
    trained["eval"] = ev
    results["pinn"] = {k: v for k, v in trained["metrics"].items()
                       if k != "loss_history"}
    results["pinn"]["rel_l2_full"] = ev["rel_l2_full"]
    results["pinn"]["rel_l2_real"] = ev["rel_l2_real"]
    results["pinn"]["rel_l2_imag"] = ev["rel_l2_imag"]
    results["pinn"]["cuts_rel_l2"] = {k: c["rel_l2"]
                                      for k, c in ev["cuts"].items()}
    results["pinn"]["paper_rel_l2"] = params["reference"]["paper_rel_l2"]

    if not fast:
        tol = params["reference"]["accept_rel_l2"]
        assert ev["rel_l2_full"] < tol, {k: results["pinn"][k] for k in
                                         ("rel_l2_full", "paper_rel_l2")}

    if make_plot:
        from scipy.stats import qmc

        p = params["pinn"]
        x0 = qmc.LatinHypercube(d=1, seed=p["seed"]).random(
            20 if fast else p["N0"])[:, 0]
        x0 = -5.0 + 10.0 * x0
        tb = qmc.LatinHypercube(d=1, seed=p["seed"] + 1).random(
            20 if fast else p["Nb"])[:, 0]
        tb = params["engine_mapping"]["z_span_m"] * tb
        results["figures"] = _make_plots(H, z_arr, h_pred, x0, tb, trained, HERE)
    return results


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--device", default=os.environ.get("PH_PINN_DEVICE", "cpu"),
                    choices=["cpu", "cuda", "auto"],
                    help="training backend: cpu (safe default on this "
                         "machine; the amdgpu ROCm build crashed the system), "
                         "cuda (with _gpu_guardrails caps + OOM->cpu "
                         "fallback) or auto")
    ap.add_argument("--nf-chunk", type=int, default=0,
                    help="collocation-cloud subsample per iteration "
                         "(0 = paper-exact full batch of Nf=20000; e.g. "
                         "5000 cuts graph memory 4x); strong default with "
                         "any GPU backend")
    ap.add_argument("--adam-iters", type=int, default=None,
                    help="override the Adam iteration count (parameters.json "
                         "default 15000; e.g. 25000 when chunking MSE_f)")
    ap.add_argument("--resume", action="store_true",
                    help="continue training from pinn_checkpoint.pt (restores "
                         "net weights + Adam optimizer state; an 'adam@N' "
                         "checkpoint resumes Adam at iter N+1, an "
                         "lbfgs/pre-eval checkpoint skips Adam and goes "
                         "straight to LBFGS refinement)")
    ap.add_argument("--fast", action="store_true", help="short smoke run")
    ap.add_argument("--discover-lambda", action="store_true",
                    help="stretch goal: learnable lambda in the residual")
    args = ap.parse_args()
    print(json.dumps(validate(verbose=True, fast=args.fast,
                              discover_lambda=args.discover_lambda,
                              device=args.device, nf_chunk=args.nf_chunk,
                              adam_iters=args.adam_iters,
                              resume=args.resume),
                    indent=2, default=str)[:8000])
    print("\nALL RAISSI-2019 SCHRODINGER-PINN CHECKS PASSED")


if __name__ == "__main__":
    main()
